# Play with Tensor
Tensor hampir sama dengan numpy array, tetapi lebih canggih karena dapat dijalankan pada GPU. Cek kodingan di bawah untuk melihat kesamaan. Sumber notebook ini dari [PyTorch tutorial](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html) dengan penambahan perbandingan operasi di numpy

In [1]:
import numpy as np
import torch

fungsi custom print biar ga ngetik print banyak-banyak

In [2]:
def print_custom(*args):
    for tensor in args:
        print(tensor)

## Membuat Tensor
Membuat matriks 5x3 tanpa inisialisasi

In [62]:
x = np.empty([5, 3]) #bisa juga dengan memakai tuple tidak hanya list
y = torch.empty([5, 3])
z = torch.empty(5, 3) #alternatif, karena fungsi ini memakai variadic arguments

print_custom(x,y,z)

[[0.90792433 0.91262644 0.52150805]
 [0.6745688  0.84218955 0.49270619]
 [0.65176129 0.20155918 0.31414534]
 [0.45028795 0.03590557 0.72134515]
 [0.19724808 0.41346794 0.49288688]]
tensor([[-0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,     nan, -0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])
tensor([[-2.7752e-27,  3.0716e-41,  4.0638e-44],
        [ 0.0000e+00,         nan,  2.5966e+20],
        [ 4.4721e+21,  2.8799e+32,  1.3816e+31],
        [ 1.9203e+31,  3.9891e+24,  4.1996e+12],
        [ 7.5338e+28,  6.8546e-07,  8.3962e-07]])


Membuat matriks 5x3 dengan inisialisasi acak

In [4]:
x = np.random.rand(5, 3) #hanya lokasi fungsi dalam package yang berbeda, nama tetap sama
y = torch.rand(5, 3) #pakai variadic arguments juga

print_custom(x, y)

[[0.8718197  0.92944446 0.44666515]
 [0.6953249  0.64156262 0.32723488]
 [0.66583169 0.60525445 0.01627472]
 [0.58011213 0.52057785 0.85723307]
 [0.93763238 0.43332442 0.53041526]]
tensor([[0.7049, 0.3882, 0.3694],
        [0.1557, 0.6384, 0.2032],
        [0.0861, 0.9520, 0.7507],
        [0.4374, 0.3444, 0.9156],
        [0.7494, 0.7758, 0.4180]])


Membuat matriks 5x3 dengan semua elemen bernilai nol dan tipe long

In [63]:
x = np.zeros([5, 3], dtype=np.long) 
y = torch.zeros(5, 3, dtype=torch.long)

print_custom(x, y)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Membuat langsung dari data. `array` untuk numpy, `tensor` untuk pytorch

In [64]:
x = np.array([5.5, 3])
y = torch.tensor([5.5, 3])

print_custom(x, y)

[5.5 3. ]
tensor([5.5000, 3.0000])


Membuat matriks dari tensor yang sudah ada, secara default menggunakan `dtype` dan `device` bawaan. Kecuali jika kita secara eksplisit mengganti. `device` ini bisa bernilai CPU atau GPU, default sih CPU  
Operasi ini saya tidak tahu apakah ada di numpy atau tidak jadi tidak saya tulis

In [65]:
y = y.new_ones(5, 3, dtype=torch.double)      # matriks baru dengan nilai elemen satu, size berubah dari yang sebelumnya
print(y)

y = torch.randn_like(y, dtype=torch.float)    # matriks nilai elemen acak normal, diubah dtype-nya
print(y)                                      # memakai size yang sama dari sebelumnya

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.6119,  2.1684, -0.2336],
        [ 0.3517,  0.6207,  0.1538],
        [ 1.0472,  0.5362, -0.7449],
        [-2.1605,  1.0519, -1.2691],
        [ 0.3089,  0.2907,  0.3794]])


Mendapatkan ukuran matriks, antara numpy dan pytorch berbeda namanya

In [67]:
x = np.zeros([5, 3], dtype=np.long)

print(x.shape)
print(y.size()) #hasilnya berupa tuple, sehingga operasi tuple berlaku

(5, 3)
torch.Size([5, 3])


## Operasi Tensor
Kita mulai dengan penambahan. Terdapat 3 varian untuk operasi ini pada pytorch dan numpy

In [68]:
a = np.random.rand(5, 3)
b = torch.rand(5, 3)

#Syntax 1
print_custom('Syntax 1', a + x, b + y) #ingat bahwa x: array numpy dan y: tensor

#Syntax 2
print_custom('Syntax 2', np.add(a, x), torch.add(b, y))

#Syntax 3
res_np = np.empty([5, 3])
res_torch = torch.empty([5, 3]) #atau torch.empty(5, 3)
print_custom('Syntax 3', np.add(a, x, out=res_np), torch.add(b, y, out=res_torch))

Syntax 1
[[0.03306735 0.28065724 0.67647219]
 [0.90009314 0.50009791 0.21659197]
 [0.81541176 0.15005068 0.0996968 ]
 [0.94000259 0.89623905 0.89550599]
 [0.71898202 0.39892885 0.70475471]]
tensor([[-1.0838,  2.3064, -0.2076],
        [ 1.2139,  1.4440,  1.1493],
        [ 1.8450,  1.5261, -0.1707],
        [-1.4888,  1.8493, -1.2408],
        [ 0.6946,  0.6991,  1.0948]])
Syntax 2
[[0.03306735 0.28065724 0.67647219]
 [0.90009314 0.50009791 0.21659197]
 [0.81541176 0.15005068 0.0996968 ]
 [0.94000259 0.89623905 0.89550599]
 [0.71898202 0.39892885 0.70475471]]
tensor([[-1.0838,  2.3064, -0.2076],
        [ 1.2139,  1.4440,  1.1493],
        [ 1.8450,  1.5261, -0.1707],
        [-1.4888,  1.8493, -1.2408],
        [ 0.6946,  0.6991,  1.0948]])
Syntax 3
[[0.03306735 0.28065724 0.67647219]
 [0.90009314 0.50009791 0.21659197]
 [0.81541176 0.15005068 0.0996968 ]
 [0.94000259 0.89623905 0.89550599]
 [0.71898202 0.39892885 0.70475471]]
tensor([[-1.0838,  2.3064, -0.2076],
        [ 1.2139,  1.

Penambahan yang tidak perlu assign variable (inplace), lihat contoh di bawah untuk jelasnya. Tidak tahu apakah ada operasi yang sama pada numpy. Semua operasi yang diakhiri `_` akan berjalan secara inplace pada pytorch, contohnya `x.copy_(y)`, `x.t_()`

In [69]:
print(res_torch)
s = res_torch + b
res_torch.add_(b)
print_custom(s, res_torch) #hasilnya akan identik

tensor([[-1.0838,  2.3064, -0.2076],
        [ 1.2139,  1.4440,  1.1493],
        [ 1.8450,  1.5261, -0.1707],
        [-1.4888,  1.8493, -1.2408],
        [ 0.6946,  0.6991,  1.0948]])
tensor([[-0.5556,  2.4444, -0.1816],
        [ 2.0762,  2.2674,  2.1448],
        [ 2.6429,  2.5160,  0.4034],
        [-0.8171,  2.6467, -1.2125],
        [ 1.0804,  1.1074,  1.8101]])
tensor([[-0.5556,  2.4444, -0.1816],
        [ 2.0762,  2.2674,  2.1448],
        [ 2.6429,  2.5160,  0.4034],
        [-0.8171,  2.6467, -1.2125],
        [ 1.0804,  1.1074,  1.8101]])


indexing pada pytorch hampir sama dengan indexing numpy

In [70]:
print_custom(x[2,1], y[2,1])
print_custom(x[1,:], y[1,:])

0
tensor(0.5362)
[0 0 0]
tensor([0.3517, 0.6207, 0.1538])


Fungsi mengganti dimensi pada numpy dan pytorch berbeda. Pada pytorch menggunakan `x.view(dim1, dim2, ...)`

In [42]:
x = np.zeros([3,2])
y = torch.zeros([3,2])

print(x.reshape(2,3).shape, x.reshape(6).shape, x.reshape(3,-1).shape)
print(y.view(2,3).size(), y.view(6).size(), y.view(3,-1).size())

(2, 3) (6,) (3, 2)
torch.Size([2, 3]) torch.Size([6]) torch.Size([3, 2])


## Konversi antara Numpy dan PyTorch

In [73]:
a = torch.ones(5)
b = a.numpy()
print_custom(type(a), type(b)) #type adalah fungsi untuk mengetahui tipe/kelas variabel

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


Mengganti nilai pada tensor akan diikuti pergantian nilai array numpy secara otomatis

In [47]:
a.add_(1)
print_custom(a, b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Sebaliknya juga berlaku, konversi array numpy ke tensor pytorch

In [48]:
a = np.zeros(3)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print_custom(a, b)

[1. 1. 1.]
tensor([1., 1., 1.], dtype=torch.float64)


Seperti yang dibicarakan di atas, operasi tensor dapat dilakukan pada GPU. Berikut contohnya (pastikan sudah punya GPU ya)

In [61]:
assert(torch.cuda.is_available())

device = torch.device('cuda')
y = torch.ones_like(b, device=device)
b = b.to(device) #alternative, b.to('cuda')
z = y + b
print_custom(z, z.to('cpu', dtype=torch.double))

tensor([2., 2., 2.], device='cuda:0', dtype=torch.float64)
tensor([2., 2., 2.], dtype=torch.float64)
